"""empty message

Revision ID: 161d9f72a6a8
Revises: 98717da71a48
Create Date: 2020-04-13 22:46:54.469420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161d9f72a6a8'
down_revision = '98717da71a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('permissions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_role', 'permissions')
    # ### end Alembic commands ###
