"""empty message

Revision ID: 98717da71a48
Revises: cdc0c4fecbc9
Create Date: 2020-04-13 22:44:37.638319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98717da71a48'
down_revision = 'cdc0c4fecbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('desc', sa.TEXT(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_users_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cms_role_id', sa.Integer(), nullable=False),
    sa.Column('cms_user_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cms_role_id'], ['cms_role.id'], ),
    sa.ForeignKeyConstraint(['cms_user_id'], ['cms_user.id'], ),
    sa.PrimaryKeyConstraint('id', 'cms_role_id', 'cms_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cms_users_role')
    op.drop_table('cms_role')
    # ### end Alembic commands ###
